// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5hx3yuyRSyfnnkBGRcCW7Fx7FnE4LI9E',
    appId: '1:577766373699:web:7fef1ae49cb2f8fead17f6',
    messagingSenderId: '577766373699',
    projectId: 'crudtutorial-b2049',
    authDomain: 'crudtutorial-b2049.firebaseapp.com',
    storageBucket: 'crudtutorial-b2049.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyayswWoNF6xo59FC5jpuYqmF08iQ15Z0',
    appId: '1:577766373699:android:1d945098321b192fad17f6',
    messagingSenderId: '577766373699',
    projectId: 'crudtutorial-b2049',
    storageBucket: 'crudtutorial-b2049.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWkryZXjKvLseYsD4aQy0vSB2IAylTS8o',
    appId: '1:577766373699:ios:d5768a29bf517d08ad17f6',
    messagingSenderId: '577766373699',
    projectId: 'crudtutorial-b2049',
    storageBucket: 'crudtutorial-b2049.appspot.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWkryZXjKvLseYsD4aQy0vSB2IAylTS8o',
    appId: '1:577766373699:ios:d5768a29bf517d08ad17f6',
    messagingSenderId: '577766373699',
    projectId: 'crudtutorial-b2049',
    storageBucket: 'crudtutorial-b2049.appspot.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5hx3yuyRSyfnnkBGRcCW7Fx7FnE4LI9E',
    appId: '1:577766373699:web:40e9344f7ca9ab97ad17f6',
    messagingSenderId: '577766373699',
    projectId: 'crudtutorial-b2049',
    authDomain: 'crudtutorial-b2049.firebaseapp.com',
    storageBucket: 'crudtutorial-b2049.appspot.com',
  );
}
